name: MNPC
version: '${project.version}'
main: com.meedix.mnpc.MnpcPlugin
api-version: '26.1'
author: Meedix
description: High-performance packet-based NPC engine for Paper 26.1.2.
commands:
  mnpc:
    description: Manage MNPC NPCs.
    usage: /npc help
    aliases: [npc]
    permission: mnpc.admin
permissions:
  mnpc.admin:
    description: Allows managing NPCs.
    default: op
